version: "3.7"

volumes:
  kubik-database:

services:

  kubik-database:
    image: postgres:10
    container_name: kubik-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql
      - kubik-database:/var/lib/postgresql/data
