version: "3.7"

volumes:
  kubik-database:
  kubik-grafana:

services:

  kubik-database:
    image: postgres:10
    container_name: kubik-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql
      - kubik-database:/var/lib/postgresql/data

  kubik-application:
    build: .
    container_name: kubik-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_BOOT_PORT=8080
      - DATABASE_URL=jdbc:postgresql://kubik-database:5432/kubik
    depends_on:
      - kubik-database

  kubik-prometheus:
    image: prom/prometheus:v2.38.0
    container_name: kubik-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    depends_on:
      - kubik-application

  kubik-grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: kubik-grafana
    depends_on:
      - kubik-prometheus
    ports:
      - "3000:3000"
    volumes:
      - kubik-grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
