server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always

general:
  time-zone: UTC
  local-datetime-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  local-date-format: yyyy-MM-dd

spring:
  application:
    name: Kubik
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kubik
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      default_schema: public
      format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    liquibase-schema: public
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    date-format: ${general.local-datetime-format}
    time-zone: ${general.time-zone}
