apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/grafana"
  claimRef:
    name: grafana-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dpl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: grafana-dpl
  template:
    metadata:
      labels:
        app: grafana-dpl
    spec:
      securityContext:
        # runAsUser: 472
        # runAsGroup: 0
        fsGroup: 472
        supplementalGroups:
          - 0
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
        - image: grafana/grafana:9.1.0
          name: grafana
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_SERVER_DOMAIN
              value: localhost
          ports:
            - name: grafana-port
              containerPort: 3000
          # volumeMounts:
            # - name: grafana-volume
            #   mountPath: /var/lib/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: grafana-dpl
