apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubik-dpl
  name: kubik-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubik-dpl
  template:
    metadata:
      labels:
        app: kubik-dpl
    spec:
      containers:
        - image: flathumor/kubik:2.4-lite
          name: kubik-db
          env:
            - name: SPRING_BOOT_PORT
              value: "9090"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-svc:5432/kubik"
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubik-svc
  name: kubik-svc
spec:
  ports:
    - name: kubik-svc-port
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: kubik-dpl
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubik-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: kubik-svc
                port:
                  number: 9090
