apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kubik-db
  name: kubik-db
  namespace: kubik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubik-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubik-db
    spec:
      containers:
        - image: flathumor/kubik:2.4-lite
          name: kubik-db
          env:
            - name: SPRING_BOOT_PORT
              value: "9090"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres:5432/kubik"
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubik-db
  name: kubik-db
  namespace: kubik
spec:
  ports:
    - name: 9090-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: kubik-db
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubik-ingress
  namespace: kubik
spec:
  rules:
    - host: kubik.sudnev.local
      http:
        paths:
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: kubik-db
                port:
                  number: 9090
  tls:
    - hosts:
      - kubik.sudnev.local
      secretName: kubik-tls-secret
