apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  namespace: default
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'Spring Boot Application input'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 3s
        static_configs:
          - targets: ['localhost:8080']
            labels:
              application: 'Kubik Application'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dpl
  template:
    metadata:
      labels:
        app: prometheus-dpl
    spec:
      volumes:
        - name: prometheus-conf-volume
          configMap:
            defaultMode: 420
            name: prometheus-cm
      containers:
        - name: prometheus
          image: prom/prometheus:v2.38.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-conf-volume
              mountPath: /etc/prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: ClusterIP
  ports:
    - port: 9090
  selector:
    app: prometheus-dpl
